title: Mickey MacLean # your name (or website title) here
logo: "/images/mick1-modified.png?raw=true" # your photo (or logo) here
description: > 
  My name is Makala (Mickey) MacLean, welcome to my portfolio! I completed my undergraduate degree at the University of Massachusetts Amherst in 2020 where I studied Physics & Observational Astronomy.
  I’m passionate about collecting & understanding data in a variety of contexts.
  <br><br>
  <a href="https://www.linkedin.com/in/makala-maclean-59bb62227/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
