title: Mickey MacLean # your name (or website title) here
logo: "/images/mick1-modified.png?raw=true" # your photo (or logo) here
description: > My name is Mickey MacLean!
  <br><br> 
I like data.Python, MatLab, Excel, SQL, LaTex
  <br><br>
  <a href="https://www.linkedin.com/in/makala-maclean-59bb62227/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
